apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-depl
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: pushpakumara/product-service:v14
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: product-service-svc
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
  - port: 8081
    targetPort: 8081
