name: Notification Service CI

# the magic is here
# run this CI only change notification-service folder.
on:
  push:
    branches: [ main ]
    paths:
      - 'notification-service/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'notification-service/**'

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # Build and Test Spring Boot App
      - name: Build with Maven
        run: |
          cd notification-service
          mvn clean package

      # Docker Build (next step will push the image to docker hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./notification-service
          file: ./notification-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/notification-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/notification-service:v${{ github.run_number }}

      - name: Update Image Tag in K8s Manifest
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          sed -i "s|image: pushpakumara/notification-service:.*|image: pushpakumara/notification-service:${{ github.run_number }}|g" k8s/notification-service-depl.yaml

      - name: Commit and Push Changes back to Main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/notification-service-depl.yaml
                
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          git commit -m "chore(cd): update notification-service image to ${{ github.run_number }} [skip ci]" || echo "No changes"  
          git push origin main